# Task 1

In [14]:
# Question 1

def exp_fun():
    return 5/0

try:
    exp_fun()
except ZeroDivisionError:
    print("Division by zero can't be done!")
except Exception:
    print("Found an exception")

Division by zero can't be done!


In [19]:
# Question 2

subjects=["Americans ","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"] 

sentence = [(sub+' '+vrb+' '+obj+".") for sub in subjects for vrb in verbs for obj in objects]
for sent in sentence:
    print(sent)

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2

In [21]:
# Question 1

# Creating a matrix with vectors as input

import numpy as np
v = np.array([2,4,6,8,9])
n = 5
matrix = np.column_stack([v**(n-i-1) for i in range(n)])
print(matrix)

[[  16    8    4    2    1]
 [ 256   64   16    4    1]
 [1296  216   36    6    1]
 [4096  512   64    8    1]
 [6561  729   81    9    1]]
